name: Deploy ke VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy
        run: |
          cd /var/www/pinote
          sudo git reset --hard origin/main
          sudo git pull origin main
          sudo npm --prefix backend install
          sudo npm --prefix frontend install
          sudo npm run build
          sudo npm --prefix backend run db:migrate
          sudo pm2 restart pinote-api pinote-worker
          sudo pm2 save
